# Generated by Django 5.1.6 on 2025-03-31 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchidea', '0002_remove_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
