# Generated by Django 5.1.6 on 2025-04-14 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidea', '0004_remove_appointment_customer_remove_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillcandidate',
            name='recruitment_form',
        ),
        migrations.RemoveField(
            model_name='skillcandidate',
            name='skill',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='appointment',
            new_name='appointment_ID',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='customer',
            new_name='customer_ID',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='employee',
            new_name='employee_ID',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='user',
            new_name='user_ID',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='user_ID',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='user_ID',
        ),
        migrations.RenameField(
            model_name='employeeskill',
            old_name='employee',
            new_name='employee_ID',
        ),
        migrations.RenameField(
            model_name='employeeskill',
            old_name='skill',
            new_name='skill_ID',
        ),
        migrations.RenameField(
            model_name='recruitmentform',
            old_name='candidate',
            new_name='candidate_ID',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='Cust@Cust.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Cust', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchidea.recruitmentform')),
                ('skill_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchidea.skill')),
            ],
        ),
        migrations.AddField(
            model_name='recruitmentform',
            name='cand_Skills',
            field=models.ManyToManyField(through='orchidea.CandidateSkill', to='orchidea.skill'),
        ),
        migrations.CreateModel(
            name='RecruitmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchidea.employee')),
                ('form_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchidea.recruitmentform')),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeRecruitment',
        ),
        migrations.DeleteModel(
            name='SkillCandidate',
        ),
    ]
