# Generated by Django 5.1.6 on 2025-04-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidea', '0005_remove_skillcandidate_recruitment_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cost',
        ),
        migrations.AddField(
            model_name='appointment',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
