# Generated by Django 5.1.6 on 2025-04-23 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchidea', '0007_remove_employeeskill_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeskill',
            unique_together={('employee', 'skill')},
        ),
    ]
