# Generated by Django 5.1.6 on 2025-04-24 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidea', '0008_alter_employeeskill_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateskill',
            name='form_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skills', to='orchidea.recruitmentform'),
        ),
        migrations.AlterField(
            model_name='candidateskill',
            name='skill_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skills', to='orchidea.skill'),
        ),
    ]
