# Generated by Django 5.1.6 on 2025-04-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidea', '0009_alter_candidateskill_form_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentform',
            name='cand_Skills',
            field=models.ManyToManyField(related_name='recruitment_forms', through='orchidea.CandidateSkill', to='orchidea.skill'),
        ),
    ]
