# Generated by Django 5.1.6 on 2025-04-27 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidea', '0010_alter_recruitmentform_cand_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(through='orchidea.EmployeeSkill', to='orchidea.skill'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='appointment_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='orchidea.appointment'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='orchidea.customer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='employee_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='orchidea.employee'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='user_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='orchidea.user'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='orchidea.user'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='orchidea.user'),
        ),
        migrations.AlterField(
            model_name='recruitmentform',
            name='candidate_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_forms', to='orchidea.candidate'),
        ),
        migrations.AlterField(
            model_name='recruitmentreview',
            name='employee_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_reviews', to='orchidea.employee'),
        ),
        migrations.AlterField(
            model_name='recruitmentreview',
            name='form_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_reviews', to='orchidea.recruitmentform'),
        ),
    ]
