# Generated by Django 5.1.6 on 2025-03-30 11:59

import django.db.models.deletion
import orchidea.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee'), ('candidate', 'Candidate')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_service', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=orchidea.models.default_appointment_date)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchidea.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchidea.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], max_length=50)),
                ('date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchidea.appointment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchidea.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchidea.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchidea.candidate')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchidea.employee')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchidea.candidate')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchidea.customer')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(related_name='employees', to='orchidea.skill'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(related_name='candidates', to='orchidea.skill'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orchidea.user'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orchidea.user'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orchidea.user'),
        ),
    ]
