# Generated by Django 5.1.6 on 2025-04-12 13:02

import datetime
import django.db.models.deletion
import django.utils.timezone
import orchidea.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidea', '0003_remove_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='type_of_service',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='recruitmentform',
            name='customer',
        ),
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.CharField(default='No description', max_length=200),
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default='Default Appointment', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='recruitmentform',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=orchidea.models.default_appointment_date),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='recruitmentform',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(default='default_skill', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='default_password', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_username', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='EmployeeRecruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchidea.employee')),
                ('recruitment_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchidea.recruitmentform')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchidea.employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchidea.skill')),
            ],
        ),
        migrations.CreateModel(
            name='SkillCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruitment_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchidea.recruitmentform')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchidea.skill')),
            ],
        ),
        migrations.DeleteModel(
            name='EmploymentForm',
        ),
    ]
