# Generated by Django 5.1.6 on 2025-04-23 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchidea', '0006_remove_booking_cost_appointment_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeskill',
            name='employee_ID',
        ),
        migrations.RemoveField(
            model_name='employeeskill',
            name='skill_ID',
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_skills', to='orchidea.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='skill',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='skill_employees', to='orchidea.skill'),
            preserve_default=False,
        ),
    ]
